import os

def parse_map_file(filepath):
    """Parses .map or .txt files. Returns list of (R,G,B) tuples."""
    palette = []
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip comments and empty lines
                if not line or line.startswith('#') or line.startswith(';'):
                    continue
                
                parts = line.split()
                if len(parts) >= 3:
                    try:
                        r, g, b = map(int, parts[:3])
                        if 0 <= r <= 255 and 0 <= g <= 255 and 0 <= b <= 255:
                            palette.append((r, g, b))
                    except ValueError:
                        continue
    except Exception as e:
        print(f"Error reading file: {e}")
    return palette

def save_map_file(palette, filepath):
    """Saves palette to .map format."""
    try:
        with open(filepath, 'w') as f:
            # Standard MAP file header comment
            f.write("# Generated by DuckPalette\n")
            for r, g, b in palette:
                f.write(f"{r:3d} {g:3d} {b:3d}\n")
        return True
    except Exception as e:
        print(f"Error writing file: {e}")
        return False